---
- block:
  - name: Use the default answerfile
    template:
      src: answerfile_{{ ovirt_engine_setup_version }}_basic.txt.j2
      dest: /tmp/answerfile.txt
      mode: 0600
      owner: root
      group: root
    when: ovirt_engine_setup_answer_file_path is undefined

  - name: Copy custom answer file
    no_log: "True"
    template:
      src: "{{ ovirt_engine_setup_answer_file_path }}"
      dest: /tmp/answerfile.txt
      mode: 0600
      owner: root
      group: root
    when: ovirt_engine_setup_answer_file_path is defined

  - name: Update setup packages
    yum:
      name: 'ovirt*setup*'
      state: latest
    when: ovirt_engine_setup_update_packages
    tags:
      - skip_ansible_lint

  - name: Run engine-setup with answerfile
    command: 'engine-setup --config-append=/tmp/answerfile.txt'
    tags:
      - skip_ansible_lint

  - name: Make sure `ovirt-engine` service is running
    service:
      name: ovirt-engine
      state: started

  - name: Check if Engine health page is up
    uri:
      url: "http://{{ ansible_fqdn }}/ovirt-engine/services/health"
      status_code: 200
    register: health_page
    retries: 12
    delay: 10
    until: health_page|success

  always:
    - name: Clean temporary files
      file:
        path: '/tmp/answerfile.txt'
        state: 'absent'
